<a href="https://colab.research.google.com/github/andresmagonzalez/python-proyect/blob/main/desafio4_emilio_martinez_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Desafio 4
 Para desarrollar este desafío necesitarás el archivo
resumen_resultados_astronautas.csv
● El IMC es una medida importante que nos ayuda a determinar si una persona
tiene un peso saludable para poder ser un astronauta. Para calcularlo se utiliza la
fórmula
IMC = m / h*h
Donde m corresponde al peso del astronauta en kilogramos, y h su estatura en metros
El rendimiento en las diferentes evaluaciones permitirá también aceptar o rechazar a los
postulantes. Para ello:

1. Crea un DataFrame con el archivo entregado.

In [ ]:
import pandas as pd

## #Crear el DataFrame a partir del archivo CSV entregado

In [ ]:
df_astronautas = pd.read_csv('resumen_resultados_astronautas.csv')

# #Mostrar las primeras filas para verificar la lectura correcta

In [ ]:
print(df_astronautas.head())

            nombre  edad  peso  altura  evaluacion_fisica  \
0    Alana Morillo    32    75     180                 93
1   Fátima Tafalla    27    68     167                 82
2       Sofía Puig    29    80     185                 85
3  Valentina Tasis    30    65     175                 90
4   Regina Cicerón    31    76     183                 89

   evaluacion_psicologica  evaluacion_adaptativa  evaluacion_medica  \
0                      88                     78                 89
1                      95                     81                 87
2                      80                     90                 91
3                      91                     85                 92
4                      87                     83                 90

   anos_experiencia califica
0                 6       Si
1                 4       Si
2                 3       Si
3                 2       No
4                 7       Si

2. Crea la columna "IMC" usando la fórmula entregada.

In [ ]:
df_astronautas["altura"] = df_astronautas["altura"] / 100

In [ ]:
df_astronautas["IMC"] = df_astronautas["peso"] / (df_astronautas["altura"] ** 2)

In [ ]:
df_astronautas.head()

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,1.80,93,88,78,89,6,Si,23.148148,87.00
1,Fátima Tafalla,27,68,1.67,82,95,81,87,4,Si,24.382373,86.25
2,Sofía Puig,29,80,1.85,85,80,90,91,3,Si,23.374726,86.50
3,Valentina Tasis,30,65,1.75,90,91,85,92,2,No,21.224490,89.50
4,Regina Cicerón,31,76,1.83,89,87,83,90,7,Si,22.694019,87.25

3. Crea la columna "promedio_evaluaciones" con el promedio de las 4 columnas
de evaluaciones. Si el IMC está entre 18.5 y 24.9, entonces el candidato
tendrá un IMC adecuado para ser astronauta. Filtra el DataFrame para
obtener solo aquellas filas donde el IMC esté dentro de los límites
entregados.

# 3.1. Crear la columna "promedio_evaluaciones"

In [ ]:
columnas_evaluaciones = [
    "evaluacion_fisica",
    "evaluacion_psicologica",
    "evaluacion_adaptativa",
    "evaluacion_medica",
]

# Calculamos el promedio de esas 4 columnas a lo largo de las filas (axis=1)

In [ ]:
df_astronautas["promedio_evaluaciones"] = df_astronautas[columnas_evaluaciones].mean(axis=1)

# 3.2. Filtrar el DataFrame según el rango de IMC adecuado (entre 18.5 y 24.9)
# Usamos .between() que incluye ambos límites por defecto

In [ ]:
df_astronautas_filtrado = df_astronautas[df_astronautas["IMC"].between(18.5, 24.9)]

# Mostrar los candidatos preseleccionados

In [ ]:
print(f"Cantidad de candidatos con IMC adecuado: {len(df_astronautas_filtrado)}")
df_astronautas_filtrado.head()

Cantidad de candidatos con IMC adecuado: 28

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,1.80,93,88,78,89,6,Si,23.148148,87.00
1,Fátima Tafalla,27,68,1.67,82,95,81,87,4,Si,24.382373,86.25
2,Sofía Puig,29,80,1.85,85,80,90,91,3,Si,23.374726,86.50
3,Valentina Tasis,30,65,1.75,90,91,85,92,2,No,21.224490,89.50
4,Regina Cicerón,31,76,1.83,89,87,83,90,7,Si,22.694019,87.25

4. El promedio de las 4 evaluaciones debe ser mayor o igual a 87. Filtra el
DataFrame resultante y agrega esta condición al filtro aplicado en el paso
anterior.

# 4. Combinar ambas condiciones en un solo filtro
# Condición 1: IMC entre 18.5 y 24.9
# Condición 2: promedio_evaluaciones mayor o igual a 87

In [ ]:
df_astronautas_final = df_astronautas[(df_astronautas["IMC"].between(18.5, 24.9)) & (df_astronautas["promedio_evaluaciones"] >= 87)]

In [ ]:
print(f"Cantidad de candidatos que cumplen todos los requisitos: {len(df_astronautas_final)}")

Cantidad de candidatos que cumplen todos los requisitos: 12

In [ ]:
df_astronautas_final.head()

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,1.80,93,88,78,89,6,Si,23.148148,87.00
3,Valentina Tasis,30,65,1.75,90,91,85,92,2,No,21.224490,89.50
4,Regina Cicerón,31,76,1.83,89,87,83,90,7,Si,22.694019,87.25
6,María Juderías,28,78,1.82,88,85,87,92,5,Si,23.547881,88.00
8,Consuela Arboleda,33,77,1.88,94,83,89,93,8,Si,21.785876,89.75

5. Reinicia el índice del DataFrame resultante.

In [ ]:
# Reiniciar el índice del DataFrame resultante
df_astronautas_final = df_astronautas_final.reset_index(drop=True)

# Mostrar el DataFrame con el nuevo índice ordenado
df_astronautas_final.head()

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,1.80,93,88,78,89,6,Si,23.148148,87.00
1,Valentina Tasis,30,65,1.75,90,91,85,92,2,No,21.224490,89.50
2,Regina Cicerón,31,76,1.83,89,87,83,90,7,Si,22.694019,87.25
3,María Juderías,28,78,1.82,88,85,87,92,5,Si,23.547881,88.00
4,Consuela Arboleda,33,77,1.88,94,83,89,93,8,Si,21.785876,89.75

In [ ]:
# 6. Modificar o crear la columna "califica" con el valor "Si"
df_astronautas_final["califica"] = "Si"

# Mostrar el DataFrame final para verificar el cambio
df_astronautas_final.head()

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,1.80,93,88,78,89,6,Si,23.148148,87.00
1,Valentina Tasis,30,65,1.75,90,91,85,92,2,Si,21.224490,89.50
2,Regina Cicerón,31,76,1.83,89,87,83,90,7,Si,22.694019,87.25
3,María Juderías,28,78,1.82,88,85,87,92,5,Si,23.547881,88.00
4,Consuela Arboleda,33,77,1.88,94,83,89,93,8,Si,21.785876,89.75

In [ ]:
# 7. Exportar el DataFrame resultante a un archivo CSV separado por comas
df_astronautas_final.to_csv("astronautas_calificados.csv", index=False, sep=",")

print("¡El archivo 'astronautas_calificados.csv' ha sido creado con éxito!")

¡El archivo 'astronautas_calificados.csv' ha sido creado con éxito!